### ISSUE TITLE
Refreshing not clearing username field for login on firefox

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#4]
Bug Name: Refreshing not clearing username field for login on firefox
Bug ID: 04
Area Path: STAR Login
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 04/12/2015
Reason: Defect
Status: Open
Environment: Firefox verison 42.0,

Description:
Refresh does not clear the username field for login when using firefox, works fine on other browsers.

Steps To Reproduce:
1) Open STAR login page on
2) Click username field
3) Enter something
4) Refresh page
5) Observe data remains

**Comment by thaffendenplanit** [comment]
This issue now seems to also occur on I.E

**Comment by VijayBrar** [comment]
@thaffendenplanit Firefox has a really strange way of refreshing the page. If you notice, it doesn't refresh completely it just does a rudimentary scan for major page changes. If you highlight the web address and press enter, it performs a partial refresh. The majority of the time, site and history data must be cleared in order to truly display pages correctly.

I've added a line in to force clear fields on refresh which should cover all other browsers.

Please retest.

**Comment by thaffendenplanit** [comment]
This is still an issue on personal details with fields not clearing after a refresh for firefox and I.E.
